### ISSUE TITLE
Consider table redesign

### ISSUE THREAD

**Issue by GaryHilares** [starlightknown/starlightknown#11]
In the following table:
![image](https://user-images.githubusercontent.com/46727048/117092888-1acd7600-ad25-11eb-9363-f273333bda89.png)

There is much space for the small logos in each space. However, GitHub seems to do not allow users to set table width in percentages. Width value can still be set in pixels, but this would not be the same in terms of responsiveness, although it is already limited by GitHub. Anyway, we should consider to whether make a table redesign or not.

**Comment by GaryHilares** [comment]
I have created #12 regarding the possible alternative with widths in pixels and some oher changes.

**Comment by starlightknown** [comment]
Merged, thank you
